development:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: dbc-teacher_development
  pool:     5
  username: your-username
  password: your-password-always-git-ignore-database.yml
  template: template0

test:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: dbc-teacher_test
  pool:     5
  username: your-username
  password: your-password-always-git-ignore-database.yml
  template: template0
