# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c3c3987fa2f8baa6ed1f2914fea8b3e139db5a8d2dbf4a3c715cd2a2846c1bff539eaed22da4e24e311200a0434fdfeb5d7bf1016087ecac05ed77f9450c88a

test:
  secret_key_base: bcea6f809318ee1c49e37f06a5d629420b3fba6524505bd9d4ac057741fe13eb30340ef84fc513c05748107df6287826c35d098d7b428665f5793068d7e44a40

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
